#!/bin/zsh

ruby correct_format_and_output.rb output/yokohama_output.txt formatted/yokohama_output.xls
ruby correct_format_and_output.rb output/kyoto_output.txt formatted/kyoto_output.xls
ruby correct_format_and_output.rb output/saitama_output.txt formatted/saitama_output.xls
ruby correct_format_and_output.rb output/kawaguchi_output.txt formatted/kawaguchi_output.xls
ruby correct_format_and_output.rb output/kawagoe_output.txt formatted/kawagoe_output.xls
ruby correct_format_and_output.rb output/kawasaki_output.txt formatted/kawasaki_output.xls
ruby correct_format_and_output.rb output/sagamihara_output.txt formatted/sagamihara_output.xls
ruby correct_format_and_output.rb output/fujisawa_output.txt formatted/fujisawa_output.xls
ruby correct_format_and_output.rb output/chigasaki_output.txt formatted/chigasaki_output.xls
ruby correct_format_and_output.rb output/chiba_output.txt formatted/chiba_output.xls
ruby correct_format_and_output.rb output/funabashi_output.txt formatted/funabashi_output.xls
ruby correct_format_and_output.rb output/ichikawa_output.txt formatted/ichikawa_output.xls
ruby correct_format_and_output.rb output/kashiwa_output.txt formatted/kashiwa_output.xls
ruby correct_format_and_output.rb output/matsudo_output.txt formatted/matsudo_output.xls
ruby correct_format_and_output.rb output/osaka_output.txt formatted/osaka_output.xls
ruby correct_format_and_output.rb output/maikata_output.txt formatted/maikata_output.xls
ruby correct_format_and_output.rb output/sakai_output.txt formatted/sakai_output.xls
ruby correct_format_and_output.rb output/setagaya_output.txt formatted/setagaya_output.xls
ruby correct_format_and_output.rb output/suginami_output.txt formatted/suginami_output.xls
ruby correct_format_and_output.rb output/minato_output.txt formatted/minato_output.xls
ruby correct_format_and_output.rb output/meguro_output.txt formatted/meguro_output.xls
ruby correct_format_and_output.rb output/chuo_output.txt formatted/chuo_output.xls
ruby correct_format_and_output.rb output/nakano_output.txt formatted/nakano_output.xls
ruby correct_format_and_output.rb output/edogawa_output.txt formatted/edogawa_output.xls
ruby correct_format_and_output.rb output/adachi_output.txt formatted/adachi_output.xls
ruby correct_format_and_output.rb output/itabashi_output.txt formatted/itabashi_output.xls
ruby correct_format_and_output.rb output/katsushika_output.txt formatted/katsushika_output.xls
ruby correct_format_and_output.rb output/toshima_output.txt formatted/toshima_output.xls
ruby correct_format_and_output.rb output/machida_output.txt formatted/machida_output.xls
ruby correct_format_and_output.rb output/sumida_output.txt formatted/sumida_output.xls
ruby correct_format_and_output.rb output/chiyoda_output.txt formatted/chiyoda_output.xls
ruby correct_format_and_output.rb output/kita_output.txt formatted/kita_output.xls
ruby correct_format_and_output.rb output/kobe_output.txt formatted/kobe_output.xls