#!/bin/zsh
touch 京都市/京都市.txt
touch さいたま市/さいたま市.txt
touch 川口市/川口市.txt
touch 川越市/川越市.txt
touch 横浜市/横浜市.txt
touch 川崎市/川崎市.txt
touch 相模原市/相模原市.txt
touch 藤沢市/藤沢市.txt
touch 茅ヶ崎市/茅ヶ崎市.txt
touch 千葉市/千葉市.txt
touch 船橋市/船橋市.txt
touch 市川市/市川市.txt
touch 柏市/柏市.txt
touch 松戸市/松戸市.txt
touch 大阪市/大阪市.txt
touch 枚方市/枚方市.txt
touch 堺市/堺市.txt
touch 世田谷区/世田谷区.txt
touch 杉並区/杉並区.txt
touch 港区/港区.txt
touch 目黒区/目黒区.txt
touch 練馬区/練馬区.txt
touch 中央区/中央区.txt
touch 中野区/中野区.txt
touch 江戸川区/江戸川区.txt
touch 足立区/足立区.txt
touch 板橋区/板橋区.txt
touch 葛飾区/葛飾区.txt
touch 豊島区/豊島区.txt
touch 町田市/町田市.txt
touch 墨田区/墨田区.txt
touch 千代田区/千代田区.txt
touch 北区/北区.txt
touch 神戸市/神戸市.txt