#!/bin/zsh
cat 京都市/京都市.txt
cat さいたま市/さいたま市.txt
cat 川口市/川口市.txt
cat 川越市/川越市.txt
cat 横浜市/横浜市.txt
cat 川崎市/川崎市.txt
cat 相模原市/相模原市.txt
cat 藤沢市/藤沢市.txt
cat 茅ヶ崎市/茅ヶ崎市.txt
cat 千葉市/千葉市.txt
cat 船橋市/船橋市.txt
cat 市川市/市川市.txt
cat 柏市/柏市.txt
cat 松戸市/松戸市.txt
cat 大阪市/大阪市.txt
cat 枚方市/枚方市.txt
cat 堺市/堺市.txt
cat 世田谷区/世田谷区.txt
cat 杉並区/杉並区.txt
cat 港区/港区.txt
cat 目黒区/目黒区.txt
cat 練馬区/練馬区.txt
cat 中央区/中央区.txt
cat 中野区/中野区.txt
cat 江戸川区/江戸川区.txt
cat 足立区/足立区.txt
cat 板橋区/板橋区.txt
cat 葛飾区/葛飾区.txt
cat 豊島区/豊島区.txt
cat 町田市/町田市.txt
cat 墨田区/墨田区.txt
cat 千代田区/千代田区.txt
cat 北区/北区.txt
cat 神戸市/神戸市.txt